import type {
  Agent,
  Broker,
  Claim,
  DocumentItem,
  JournalEntry,
  Lead,
  NotificationItem,
  Participant,
  Payment,
  Policy,
  Product,
  Quote,
  SessionUser,
  SurplusPeriod,
  Ticket,
  Treaty,
  AmlScreening,
  AuditLogEntry,
  ReinsuranceCession,
  ReinsuranceRecovery,
} from "./types";

export const operator = {
  name: "InsuraX Kenya",
  license: "IRA/INS/2024/014",
  model: "Wakala",
  wakalaRate: 0.15,
  currency: "KES",
  shariahBoard: "InsuraX Shariah Supervisory Board",
};

export const demoUsers: SessionUser[] = [
  {
    id: "u-part",
    name: "Amina Wanjiku",
    email: "amina@example.com",
    phone: "+254711000111",
    role: "participant",
    branch: "Nairobi CBD",
    participantId: "p-1",
  },
  {
    id: "u-agent",
    name: "Joseph Otieno",
    email: "joseph.agent@insurax.africa",
    phone: "+254722111222",
    role: "agent",
    branch: "Kisumu",
    agentId: "a-1",
  },
  {
    id: "u-broker",
    name: "Zahra Insurance Brokers",
    email: "ops@zahrabrokers.co.ke",
    phone: "+254733222333",
    role: "broker",
    branch: "Nairobi CBD",
    brokerId: "b-1",
  },
  {
    id: "u-uw",
    name: "Fatma Hassan",
    email: "fatma.uw@insurax.africa",
    phone: "+254700111222",
    role: "underwriter",
    branch: "Nairobi CBD",
  },
  {
    id: "u-claims",
    name: "Daniel Kariuki",
    email: "daniel.claims@insurax.africa",
    phone: "+254700333444",
    role: "claims_officer",
    branch: "Nairobi CBD",
  },
  {
    id: "u-assessor",
    name: "James Omondi",
    email: "james.assessor@insurax.africa",
    phone: "+254700444555",
    role: "claims_assessor",
    branch: "Nairobi CBD",
  },
  {
    id: "u-fin",
    name: "Grace Njeri",
    email: "grace.finance@insurax.africa",
    phone: "+254700555666",
    role: "finance",
    branch: "Nairobi CBD",
  },
  {
    id: "u-comp",
    name: "Ibrahim Ali",
    email: "ibrahim.compliance@insurax.africa",
    phone: "+254700777888",
    role: "compliance",
    branch: "Nairobi CBD",
  },
  {
    id: "u-shariah",
    name: "Sheikh Yusuf Noor",
    email: "shariah@insurax.africa",
    phone: "+254700999000",
    role: "shariah_officer",
    branch: "Mombasa",
  },
  {
    id: "u-admin",
    name: "Platform Admin",
    email: "admin@insurax.africa",
    phone: "+254700000001",
    role: "admin",
    branch: "Nairobi CBD",
  },
  {
    id: "u-cc",
    name: "Mercy Achieng",
    email: "mercy.cc@insurax.africa",
    phone: "+254701010101",
    role: "call_center",
    branch: "Nairobi CBD",
  },
  {
    id: "u-bm",
    name: "Peter Kamau",
    email: "peter.nakuru@insurax.africa",
    phone: "+254702020202",
    role: "branch_manager",
    branch: "Nakuru",
  },
];

export const products: Product[] = [
  {
    id: "prd-motor",
    slug: "motor-comprehensive",
    code: "MOT-COMP",
    name: "Motor Comprehensive Takaful",
    line: "motor",
    summary: "Own damage, third party, theft and windscreen for private cars.",
    description:
      "Shariah-compliant motor cover with digital certificates, garage cashless repair network, and same-day claim intake from the app.",
    model: "wakala",
    frequencies: ["monthly", "annually"],
    minContribution: 18000,
    maxSumCovered: 8000000,
    waitingDays: 0,
    wakalaRate: 0.15,
    isMicro: false,
    shariahApproved: true,
    covers: [
      { code: "OD", name: "Own damage" },
      { code: "TPPD", name: "Third party property" },
      { code: "TPBI", name: "Third party injury" },
      { code: "THEFT", name: "Theft" },
      { code: "WS", name: "Windscreen", optional: true },
    ],
    baseRate: 0.045,
    ratingBasis: "sum_covered",
  },
  {
    id: "prd-boda",
    slug: "boda-micro",
    code: "MIC-BODA",
    name: "Boda Boda Micro Takaful",
    line: "micro",
    summary: "Daily or weekly cover for riders via M-Pesa.",
    description: "Embedded micro cover for riders and passengers with USSD and STK push contributions.",
    model: "wakala",
    frequencies: ["daily", "weekly", "monthly"],
    minContribution: 30,
    maxSumCovered: 250000,
    waitingDays: 1,
    wakalaRate: 0.18,
    isMicro: true,
    shariahApproved: true,
    covers: [
      { code: "PA", name: "Personal accident" },
      { code: "TP", name: "Third party" },
    ],
    baseRate: 0.12,
    ratingBasis: "flat",
  },
  {
    id: "prd-med",
    slug: "hospital-cash",
    code: "MED-CASH",
    name: "Hospital Cash Micro",
    line: "medical",
    summary: "Daily hospital cash for informal workers and SACCO members.",
    description: "Affordable inpatient cash benefit with 14-day waiting period and WhatsApp claims.",
    model: "wakala",
    frequencies: ["weekly", "monthly"],
    minContribution: 150,
    maxSumCovered: 150000,
    waitingDays: 14,
    wakalaRate: 0.12,
    isMicro: true,
    shariahApproved: true,
    covers: [{ code: "HC", name: "Hospital cash" }],
    baseRate: 0,
    ratingBasis: "age_band",
  },
  {
    id: "prd-family",
    slug: "family-takaful",
    code: "FAM-PROTECT",
    name: "Family Takaful Protect",
    line: "family_takaful",
    summary: "Term family protection with surplus sharing.",
    description: "Participant risk fund cover for death and permanent disability, with optional education rider.",
    model: "hybrid",
    frequencies: ["monthly", "annually"],
    minContribution: 1200,
    maxSumCovered: 5000000,
    waitingDays: 30,
    wakalaRate: 0.2,
    isMicro: false,
    shariahApproved: true,
    covers: [
      { code: "DEATH", name: "Death benefit" },
      { code: "PD", name: "Permanent disability" },
      { code: "EDU", name: "Education rider", optional: true },
    ],
    baseRate: 0.008,
    ratingBasis: "sum_covered",
  },
  {
    id: "prd-funeral",
    slug: "janaaza",
    code: "FUN-JANAAZA",
    name: "Janaaza Cover",
    line: "funeral",
    summary: "Immediate funeral expense support for the family.",
    description: "Fast payout funeral takaful designed for chama and mosque groups.",
    model: "wakala",
    frequencies: ["monthly", "annually"],
    minContribution: 200,
    maxSumCovered: 200000,
    waitingDays: 21,
    wakalaRate: 0.1,
    isMicro: true,
    shariahApproved: true,
    covers: [{ code: "FUN", name: "Funeral expenses" }],
    baseRate: 0.015,
    ratingBasis: "sum_covered",
  },
  {
    id: "prd-crop",
    slug: "crop-index",
    code: "AGR-CROP",
    name: "Crop Index Takaful",
    line: "agriculture",
    summary: "Weather-index cover for maize, tea and horticulture.",
    description: "Parametric payouts triggered by rainfall deviation. Built for cooperatives and county programs.",
    model: "wakala",
    frequencies: ["single", "annually"],
    minContribution: 2500,
    maxSumCovered: 2000000,
    waitingDays: 0,
    wakalaRate: 0.12,
    isMicro: false,
    shariahApproved: true,
    covers: [{ code: "DROUGHT", name: "Drought index" }, { code: "FLOOD", name: "Excess rainfall" }],
    baseRate: 0.06,
    ratingBasis: "sum_covered",
  },
  {
    id: "prd-live",
    slug: "livestock",
    code: "AGR-LIVE",
    name: "Livestock Takaful",
    line: "livestock",
    summary: "Cattle, goats and camels with photo-based onboarding.",
    description: "Agent offline enrolment, ear-tag registry and veterinary partner network.",
    model: "wakala",
    frequencies: ["monthly", "annually"],
    minContribution: 800,
    maxSumCovered: 500000,
    waitingDays: 14,
    wakalaRate: 0.14,
    isMicro: true,
    shariahApproved: true,
    covers: [{ code: "MORT", name: "Mortality" }, { code: "THEFT", name: "Theft", optional: true }],
    baseRate: 0.07,
    ratingBasis: "sum_covered",
  },
  {
    id: "prd-travel",
    slug: "travel",
    code: "TRV-AFR",
    name: "Travel Takaful",
    line: "travel",
    summary: "Schengen, Umrah and regional travel cover.",
    description: "Instant certificates for visa applications with medical emergency and baggage benefits.",
    model: "wakala",
    frequencies: ["single"],
    minContribution: 1800,
    maxSumCovered: 10000000,
    waitingDays: 0,
    wakalaRate: 0.2,
    isMicro: false,
    shariahApproved: true,
    covers: [
      { code: "MED", name: "Emergency medical" },
      { code: "BAG", name: "Baggage" },
      { code: "CXL", name: "Trip cancellation", optional: true },
    ],
    baseRate: 0.004,
    ratingBasis: "sum_covered",
  },
  {
    id: "prd-gadget",
    slug: "gadget",
    code: "GAD-DEV",
    name: "Device Shield",
    line: "gadget",
    summary: "Phones, laptops and POS devices for merchants.",
    description: "Embedded at checkout with fintechs and electronics retailers.",
    model: "wakala",
    frequencies: ["monthly", "annually"],
    minContribution: 250,
    maxSumCovered: 250000,
    waitingDays: 7,
    wakalaRate: 0.22,
    isMicro: true,
    shariahApproved: true,
    covers: [{ code: "SCREEN", name: "Screen damage" }, { code: "THEFT", name: "Theft" }],
    baseRate: 0.09,
    ratingBasis: "sum_covered",
  },
  {
    id: "prd-asset",
    slug: "asset",
    code: "AST-FIRE",
    name: "Asset & Fire Takaful",
    line: "asset",
    summary: "Shops, kiosks, SACCO offices and household contents.",
    description: "Fire, burglary and allied perils for MSMEs with flexible monthly contributions.",
    model: "wakala",
    frequencies: ["monthly", "annually"],
    minContribution: 1500,
    maxSumCovered: 20000000,
    waitingDays: 0,
    wakalaRate: 0.16,
    isMicro: false,
    shariahApproved: true,
    covers: [{ code: "FIRE", name: "Fire" }, { code: "BURG", name: "Burglary" }],
    baseRate: 0.012,
    ratingBasis: "sum_covered",
  },
];

export const participants: Participant[] = [
  {
    id: "p-1",
    name: "Amina Wanjiku",
    phone: "+254711000111",
    email: "amina@example.com",
    nationalId: "32109876",
    dob: "1994-03-12",
    county: "Nairobi",
    occupation: "Retailer",
    kyc: "verified",
    channel: "mobile",
    riskScore: 22,
    clv: 186400,
  },
  {
    id: "p-2",
    name: "Brian Kipchoge",
    phone: "+254712222333",
    email: "brian.k@example.com",
    nationalId: "29876543",
    dob: "1988-11-02",
    county: "Uasin Gishu",
    occupation: "Farmer",
    kyc: "verified",
    channel: "agent",
    riskScore: 31,
    clv: 54200,
  },
  {
    id: "p-3",
    name: "Halima Mohamed",
    phone: "+254713333444",
    email: "halima@example.com",
    nationalId: "27654321",
    dob: "1990-07-19",
    county: "Mombasa",
    occupation: "Nurse",
    kyc: "in_review",
    channel: "whatsapp",
    riskScore: 18,
    clv: 91000,
  },
  {
    id: "p-4",
    name: "Samuel Mwangi",
    phone: "+254714444555",
    email: "sam.mwangi@example.com",
    nationalId: "25432109",
    dob: "1982-01-30",
    county: "Nakuru",
    occupation: "Boda rider",
    kyc: "verified",
    channel: "ussd",
    riskScore: 44,
    clv: 12800,
  },
  {
    id: "p-5",
    name: "Linet Chebet",
    phone: "+254715555666",
    email: "linet@example.com",
    nationalId: "30987654",
    dob: "1997-09-08",
    county: "Kericho",
    occupation: "Teacher",
    kyc: "verified",
    channel: "web",
    riskScore: 15,
    clv: 240500,
  },
];

export const agents: Agent[] = [
  { id: "a-1", code: "AG-KE-0142", name: "Joseph Otieno", phone: "+254722111222", branch: "Kisumu", license: "IRA-AG-88921", wallet: 42850, ytdGwp: 12840000, target: 18000000 },
  { id: "a-2", code: "AG-KE-0208", name: "Mary Wambui", phone: "+254722333444", branch: "Nairobi CBD", license: "IRA-AG-90112", wallet: 18900, ytdGwp: 22150000, target: 25000000 },
  { id: "a-3", code: "AG-KE-0311", name: "Hassan Juma", phone: "+254722555666", branch: "Mombasa", license: "IRA-AG-77430", wallet: 7600, ytdGwp: 6420000, target: 9000000 },
];

export const brokers: Broker[] = [
  { id: "b-1", code: "BR-KE-07", name: "Zahra Insurance Brokers", license: "IRA-BR-2211", clients: 186, commissionRate: 0.125, ytdGwp: 28400000, wallet: 412000 },
  { id: "b-2", code: "BR-KE-19", name: "Savanna Risk Partners", license: "IRA-BR-3302", clients: 94, commissionRate: 0.1, ytdGwp: 11200000, wallet: 98000 },
];

export const seedQuotes: Quote[] = [
  {
    id: "q-1",
    number: "QT-2026-10482",
    participantId: "p-1",
    participantName: "Amina Wanjiku",
    productId: "prd-motor",
    productName: "Motor Comprehensive Takaful",
    agentId: "a-2",
    channel: "web",
    status: "priced",
    sumCovered: 1800000,
    frequency: "annually",
    base: 81000,
    wakala: 12150,
    tabarru: 68850,
    taxes: 0,
    levies: 364.5,
    total: 81364.5,
    monthly: 6780,
    uwDecision: "auto_accept",
    uwNotes: "Straight-through underwriting approved.",
    risk: { make: "Toyota", model: "Axio", year: 2018, vehicleAge: 8, plate: "KDA 123A" },
    createdAt: "2026-07-28T08:12:00Z",
    validUntil: "2026-08-27",
  },
  {
    id: "q-2",
    number: "QT-2026-10501",
    participantId: "p-2",
    participantName: "Brian Kipchoge",
    productId: "prd-crop",
    productName: "Crop Index Takaful",
    agentId: "a-1",
    channel: "agent",
    status: "referred",
    sumCovered: 900000,
    frequency: "single",
    base: 54000,
    wakala: 6480,
    tabarru: 47520,
    taxes: 0,
    levies: 243,
    total: 54243,
    monthly: 4520,
    uwDecision: "refer",
    uwNotes: "Sum covered above agent binding authority for county drought zone.",
    risk: { crop: "Maize", acres: 12, county: "Uasin Gishu" },
    createdAt: "2026-08-01T10:40:00Z",
    validUntil: "2026-08-31",
  },
];

export const seedPolicies: Policy[] = [
  {
    id: "pol-1",
    number: "POL-MOT-88421",
    participantId: "p-1",
    participantName: "Amina Wanjiku",
    productId: "prd-motor",
    productName: "Motor Comprehensive Takaful",
    agentId: "a-2",
    agentName: "Mary Wambui",
    branch: "Nairobi CBD",
    status: "active",
    channel: "mobile",
    inception: "2026-03-01",
    expiry: "2027-02-28",
    sumCovered: 1600000,
    contribution: 72000,
    frequency: "annually",
    wakala: 10800,
    tabarru: 61200,
    createdAt: "2026-02-26T09:00:00Z",
  },
  {
    id: "pol-2",
    number: "POL-MED-19002",
    participantId: "p-1",
    participantName: "Amina Wanjiku",
    productId: "prd-med",
    productName: "Hospital Cash Micro",
    branch: "Nairobi CBD",
    status: "active",
    channel: "whatsapp",
    inception: "2026-01-15",
    expiry: "2027-01-14",
    sumCovered: 80000,
    contribution: 2400,
    frequency: "monthly",
    wakala: 288,
    tabarru: 2112,
    createdAt: "2026-01-14T12:00:00Z",
  },
  {
    id: "pol-3",
    number: "POL-BODA-4410",
    participantId: "p-4",
    participantName: "Samuel Mwangi",
    productId: "prd-boda",
    productName: "Boda Boda Micro Takaful",
    agentId: "a-1",
    agentName: "Joseph Otieno",
    branch: "Nakuru",
    status: "active",
    channel: "ussd",
    inception: "2026-07-01",
    expiry: "2026-07-31",
    sumCovered: 200000,
    contribution: 900,
    frequency: "monthly",
    wakala: 162,
    tabarru: 738,
    createdAt: "2026-07-01T06:15:00Z",
  },
  {
    id: "pol-4",
    number: "POL-FAM-2201",
    participantId: "p-5",
    participantName: "Linet Chebet",
    productId: "prd-family",
    productName: "Family Takaful Protect",
    agentId: "a-2",
    agentName: "Mary Wambui",
    brokerId: "b-1",
    branch: "Nairobi CBD",
    status: "active",
    channel: "broker",
    inception: "2025-09-01",
    expiry: "2026-08-31",
    sumCovered: 2500000,
    contribution: 24000,
    frequency: "annually",
    wakala: 4800,
    tabarru: 19200,
    createdAt: "2025-08-20T11:00:00Z",
  },
  {
    id: "pol-5",
    number: "POL-CROP-773",
    participantId: "p-2",
    participantName: "Brian Kipchoge",
    productId: "prd-crop",
    productName: "Crop Index Takaful",
    agentId: "a-1",
    agentName: "Joseph Otieno",
    branch: "Eldoret",
    status: "expired",
    channel: "agent",
    inception: "2025-03-01",
    expiry: "2026-02-28",
    sumCovered: 600000,
    contribution: 36000,
    frequency: "single",
    wakala: 4320,
    tabarru: 31680,
    createdAt: "2025-02-18T08:00:00Z",
  },
  {
    id: "pol-6",
    number: "POL-GAD-908",
    participantId: "p-3",
    participantName: "Halima Mohamed",
    productId: "prd-gadget",
    productName: "Device Shield",
    brokerId: "b-1",
    branch: "Mombasa",
    status: "suspended",
    channel: "broker",
    inception: "2026-05-01",
    expiry: "2027-04-30",
    sumCovered: 85000,
    contribution: 7650,
    frequency: "annually",
    wakala: 1683,
    tabarru: 5967,
    createdAt: "2026-04-30T16:20:00Z",
  },
];

export const seedClaims: Claim[] = [
  {
    id: "cl-1",
    number: "CLM-2026-331",
    policyId: "pol-1",
    policyNumber: "POL-MOT-88421",
    participantId: "p-1",
    participantName: "Amina Wanjiku",
    status: "assessing",
    incidentDate: "2026-07-22",
    reportedAt: "2026-07-22T18:40:00Z",
    description: "Rear-end collision along Mombasa Road. Bumper and boot damage.",
    location: "Mombasa Rd, Nairobi",
    claimed: 186000,
    fraudScore: 18,
    assessor: "James Omondi",
    slaDue: "2026-08-05T18:40:00Z",
  },
  {
    id: "cl-2",
    number: "CLM-2026-298",
    policyId: "pol-3",
    policyNumber: "POL-BODA-4410",
    participantId: "p-4",
    participantName: "Samuel Mwangi",
    status: "fraud_check",
    incidentDate: "2026-07-18",
    reportedAt: "2026-07-18T07:05:00Z",
    description: "Passenger injury after pothole incident.",
    location: "Nakuru CBD",
    claimed: 45000,
    fraudScore: 71,
    slaDue: "2026-07-25T07:05:00Z",
  },
  {
    id: "cl-3",
    number: "CLM-2026-210",
    policyId: "pol-4",
    policyNumber: "POL-FAM-2201",
    participantId: "p-5",
    participantName: "Linet Chebet",
    status: "paid",
    incidentDate: "2026-04-02",
    reportedAt: "2026-04-03T09:12:00Z",
    description: "Hospital cash claim after 4-day admission.",
    location: "Kericho County Referral",
    claimed: 24000,
    approved: 24000,
    fraudScore: 9,
    slaDue: "2026-04-10T09:12:00Z",
  },
];

export const seedPayments: Payment[] = [
  { id: "pay-1", reference: "MPESA-SH2AB9", policyNumber: "POL-MOT-88421", participantName: "Amina Wanjiku", method: "mpesa_stk", status: "reconciled", amount: 72000, paidAt: "2026-02-26T09:04:00Z", receipt: "SH2AB9" },
  { id: "pay-2", reference: "MPESA-WK9912", policyNumber: "POL-MED-19002", participantName: "Amina Wanjiku", method: "mpesa_paybill", status: "completed", amount: 200, paidAt: "2026-08-01T06:11:00Z", receipt: "WK9912" },
  { id: "pay-3", reference: "USSD-44019", policyNumber: "POL-BODA-4410", participantName: "Samuel Mwangi", method: "mpesa_till", status: "completed", amount: 900, paidAt: "2026-07-01T06:16:00Z", receipt: "44019" },
  { id: "pay-4", reference: "CARD-8821", policyNumber: "POL-FAM-2201", participantName: "Linet Chebet", method: "card", status: "reconciled", amount: 24000, paidAt: "2025-08-20T11:08:00Z", receipt: "8821" },
  { id: "pay-5", reference: "STK-FAIL-19", policyNumber: "POL-GAD-908", participantName: "Halima Mohamed", method: "mpesa_stk", status: "failed", amount: 638, paidAt: undefined },
];

export const seedLeads: Lead[] = [
  { id: "ld-1", name: "Collins Ouma", phone: "+254716111222", productLine: "motor", status: "quoted", agentId: "a-1", notes: "Wants comprehensive for Premio 2016." },
  { id: "ld-2", name: "Faith Mutiso", phone: "+254716333444", productLine: "medical", status: "new", agentId: "a-1", notes: "SACCO group of 40 members." },
  { id: "ld-3", name: "Omar Said", phone: "+254716555666", productLine: "travel", status: "contacted", agentId: "a-3", notes: "Umrah travel in September." },
  { id: "ld-4", name: "FleetCo Logistics", phone: "+254720111000", productLine: "motor", status: "new", brokerId: "b-1", notes: "12 light trucks — bulk schedule pending." },
  { id: "ld-5", name: "Coastal SACCO", phone: "+254721222333", productLine: "medical", status: "contacted", brokerId: "b-1", notes: "220 members hospital cash." },
];

export const seedTickets: Ticket[] = [
  { id: "tk-1", subject: "Certificate not downloading", channel: "whatsapp", status: "open", priority: "high", participantName: "Amina Wanjiku", createdAt: "2026-08-04T08:22:00Z" },
  { id: "tk-2", subject: "Change vehicle registration", channel: "call", status: "pending", priority: "normal", participantName: "Halima Mohamed", createdAt: "2026-08-03T14:10:00Z" },
  { id: "tk-3", subject: "Claim status enquiry", channel: "app", status: "resolved", priority: "normal", participantName: "Samuel Mwangi", createdAt: "2026-07-20T11:00:00Z" },
];

export const seedNotifications: NotificationItem[] = [
  { id: "n-1", channel: "sms", title: "Contribution received", body: "KES 200 received for POL-MED-19002.", status: "sent", createdAt: "2026-08-01T06:12:00Z" },
  { id: "n-2", channel: "whatsapp", title: "Renewal reminder", body: "Family Takaful Protect renews on 31 Aug 2026.", status: "sent", createdAt: "2026-08-01T07:00:00Z" },
  { id: "n-3", channel: "push", title: "Claim update", body: "Assessor assigned to CLM-2026-331.", status: "sent", createdAt: "2026-07-23T09:00:00Z" },
  { id: "n-4", channel: "email", title: "Premium due", body: "Device Shield installment failed. Retry scheduled.", status: "queued", createdAt: "2026-08-05T05:30:00Z" },
];

export const seedDocuments: DocumentItem[] = [
  {
    id: "d-1",
    owner: "POL-MOT-88421",
    type: "Certificate",
    name: "Motor_Certificate_2026.html",
    createdAt: "2026-03-01T00:00:00Z",
    policyId: "pol-1",
    participantId: "p-1",
    mime: "text/html",
  },
  {
    id: "d-2",
    owner: "CLM-2026-331",
    type: "Police abstract",
    name: "Abstract_MombasaRd.txt",
    createdAt: "2026-07-22T19:10:00Z",
    claimId: "cl-1",
    participantId: "p-1",
    mime: "text/plain",
    body: "POLICE ABSTRACT\nOB 42/22/07/2026 GITHURAI\nACCIDENT ON MOMBASA RD\nVEHICLE KDA123A\nCOMPLAINANT AMINA WANJIKU",
    ocrText: "OB 42/22/07/2026 · KDA123A · AMINA WANJIKU",
  },
  {
    id: "d-3",
    owner: "CLM-2026-331",
    type: "Photos",
    name: "rear_damage_01.jpg",
    createdAt: "2026-07-22T18:45:00Z",
    claimId: "cl-1",
    participantId: "p-1",
    mime: "image/jpeg",
  },
  {
    id: "d-4",
    owner: "p-1",
    type: "KYC",
    name: "National_ID_Amina.txt",
    createdAt: "2026-02-20T10:00:00Z",
    participantId: "p-1",
    mime: "text/plain",
    body: "REPUBLIC OF KENYA\nAMINA WANJIKU\nID 32109876\nDOB 12.03.1994",
  },
];

export const treaties: Treaty[] = [
  {
    id: "tr-1",
    name: "Motor Surplus Treaty 2026",
    type: "treaty",
    reinsurer: "Africa Re",
    cessionRate: 0.3,
    from: "2026-01-01",
    to: "2026-12-31",
    cededYtd: 18420000,
    recoveriesYtd: 2100000,
    status: "active",
    lines: ["motor", "micro"],
  },
  {
    id: "tr-2",
    name: "Agri Quota Share",
    type: "treaty",
    reinsurer: "Kenya Re",
    cessionRate: 0.4,
    from: "2026-01-01",
    to: "2026-12-31",
    cededYtd: 6200000,
    recoveriesYtd: 880000,
    status: "active",
    lines: ["agriculture", "livestock"],
  },
  {
    id: "tr-3",
    name: "Large Family Fac",
    type: "facultative",
    reinsurer: "Hannover Re Takaful",
    cessionRate: 0.5,
    from: "2026-04-01",
    to: "2027-03-31",
    cededYtd: 1250000,
    recoveriesYtd: 0,
    status: "active",
    lines: ["family_takaful", "medical"],
  },
];

export const seedCessions: ReinsuranceCession[] = [
  {
    id: "ces-1",
    treatyId: "tr-1",
    treatyName: "Motor Surplus Treaty 2026",
    policyId: "pol-1",
    policyNumber: "POL-MOT-88421",
    participantName: "Amina Wanjiku",
    productLine: "motor",
    grossContribution: 72000,
    cededContribution: 21600,
    retention: 50400,
    createdAt: "2026-03-02T10:00:00Z",
  },
];

export const seedRecoveries: ReinsuranceRecovery[] = [
  {
    id: "rec-1",
    treatyId: "tr-1",
    treatyName: "Motor Surplus Treaty 2026",
    claimId: "cl-1",
    claimNumber: "CLM-2026-331",
    amount: 55800,
    status: "submitted",
    createdAt: "2026-07-25T09:00:00Z",
  },
];


export const seedJournals: JournalEntry[] = [
  { id: "j-1", date: "2026-08-01", reference: "JE-88421", memo: "Motor contribution — tabarru & wakala split", debit: 72000, credit: 72000 },
  { id: "j-2", date: "2026-08-01", reference: "JE-19002", memo: "Hospital cash installment", debit: 200, credit: 200 },
  { id: "j-3", date: "2026-07-30", reference: "JE-CLM-210", memo: "Family claim settlement", debit: 24000, credit: 24000 },
  { id: "j-4", date: "2026-07-31", reference: "JE-COMM-JUL", memo: "Agent commission accrual", debit: 980000, credit: 980000 },
];

/** @deprecated use seedJournals */
export const journals = seedJournals;

export const branches = ["Nairobi CBD", "Mombasa", "Kisumu", "Eldoret", "Nakuru"];

export const gwpByMonth = [
  { month: "Mar", gwp: 18.2, claims: 6.1 },
  { month: "Apr", gwp: 21.4, claims: 7.8 },
  { month: "May", gwp: 19.6, claims: 5.4 },
  { month: "Jun", gwp: 24.1, claims: 8.9 },
  { month: "Jul", gwp: 27.8, claims: 9.2 },
  { month: "Aug", gwp: 16.4, claims: 4.1 },
];

export const gwpByProduct = [
  { name: "Motor", value: 42 },
  { name: "Medical / micro", value: 18 },
  { name: "Family", value: 14 },
  { name: "Agriculture", value: 12 },
  { name: "Other", value: 14 },
];

export const gwpByBranch = [
  { name: "Nairobi CBD", value: 48.2 },
  { name: "Mombasa", value: 18.6 },
  { name: "Kisumu", value: 12.1 },
  { name: "Eldoret", value: 9.4 },
  { name: "Nakuru", value: 8.7 },
];

export const seedSurplusPeriods: SurplusPeriod[] = [
  {
    id: "sp-fy25",
    code: "FY25",
    label: "Financial year 2025 (provisional)",
    year: 2025,
    status: "approved",
    tabarruPool: 4200000,
    claimsCost: 2680000,
    expenses: 336000,
    investmentIncome: 147000,
    netSurplus: 1331000,
    participantPool: 931700,
    contingencyReserve: 266200,
    charityPool: 133100,
    participantShareRate: 0.7,
    contingencyRate: 0.2,
    charityRate: 0.1,
    shares: [
      {
        participantId: "p-1",
        participantName: "Amina Wanjiku",
        tabarruBase: 86000,
        shareAmount: 1840,
        status: "payable",
      },
      {
        participantId: "p-2",
        participantName: "Hassan Ali",
        tabarruBase: 42000,
        shareAmount: 920,
        status: "payable",
      },
    ],
    shariahNotes: "Approved under wakala model. Charity portion earmarked for hospital cash hardship fund.",
    declaredAt: "2026-02-15T10:00:00Z",
    decidedAt: "2026-02-28T14:00:00Z",
    decidedBy: "u-shariah",
    createdAt: "2026-02-10T09:00:00Z",
  },
];

export const seedScreenings: AmlScreening[] = [
  {
    id: "scr-1",
    participantId: "p-1",
    participantName: "Amina Wanjiku",
    type: "sanctions_peps",
    result: "clear",
    notes: "No matches on OFAC / UN / local PEPs list.",
    screenedAt: "2026-02-20T10:00:00Z",
    screenedBy: "Ibrahim Ali",
  },
  {
    id: "scr-2",
    participantId: "p-3",
    participantName: "Halima Mohamed",
    type: "aml_onboarding",
    result: "pending",
    notes: "Awaiting source-of-funds declaration.",
    screenedAt: "2026-08-02T09:15:00Z",
  },
  {
    id: "scr-3",
    participantId: "p-4",
    participantName: "Samuel Mwangi",
    type: "device_identity",
    result: "clear",
    screenedAt: "2026-07-01T14:22:00Z",
    screenedBy: "Ibrahim Ali",
  },
];

export const seedAuditLogs: AuditLogEntry[] = [
  {
    id: "aud-1",
    action: "kyc.verified",
    actor: "Ibrahim Ali",
    subject: "Amina Wanjiku",
    detail: "KYC marked verified after IPRS match.",
    createdAt: "2026-02-20T10:05:00Z",
  },
  {
    id: "aud-2",
    action: "aml.screening",
    actor: "system",
    subject: "Halima Mohamed",
    detail: "AML onboarding screening queued.",
    createdAt: "2026-08-02T09:15:00Z",
  },
];
