import type { Policy } from "@/lib/types";

/** Generate a printable HTML certificate for a policy (downloaded as .html). */
export function buildPolicyCertificateHtml(policy: Policy, operatorName = "InsuraX Kenya") {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Certificate ${policy.number}</title>
  <style>
    body { font-family: Georgia, serif; color: #0B1F33; margin: 40px; }
    .mark { letter-spacing: 0.2em; text-transform: uppercase; color: #0F766E; font-size: 12px; }
    h1 { font-size: 28px; margin: 8px 0 4px; }
    .box { border: 2px solid #C9A227; padding: 24px; margin-top: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    td { padding: 8px 0; border-bottom: 1px solid #D8E0E8; font-size: 14px; }
    td:first-child { color: #64748B; width: 40%; }
    .foot { margin-top: 32px; font-size: 12px; color: #64748B; }
  </style>
</head>
<body>
  <p class="mark">${operatorName}</p>
  <h1>Certificate of Cover</h1>
  <p>Shariah-supervised takaful · Wakala model</p>
  <div class="box">
    <table>
      <tr><td>Policy number</td><td><strong>${policy.number}</strong></td></tr>
      <tr><td>Participant</td><td>${policy.participantName}</td></tr>
      <tr><td>Product</td><td>${policy.productName}</td></tr>
      <tr><td>Sum covered</td><td>KES ${policy.sumCovered.toLocaleString()}</td></tr>
      <tr><td>Contribution</td><td>KES ${policy.contribution.toLocaleString()} / ${policy.frequency}</td></tr>
      <tr><td>Tabarru (risk fund)</td><td>KES ${policy.tabarru.toLocaleString()}</td></tr>
      <tr><td>Wakala fee</td><td>KES ${policy.wakala.toLocaleString()}</td></tr>
      <tr><td>Period</td><td>${policy.inception} → ${policy.expiry}</td></tr>
      <tr><td>Status</td><td>${policy.status}</td></tr>
      <tr><td>Channel</td><td>${policy.channel}</td></tr>
    </table>
  </div>
  <p class="foot">Generated by InsuraX · Demo certificate · Not a regulated instrument until issued from PAS with wet/digital seal.</p>
</body>
</html>`;
}

export function downloadTextFile(filename: string, content: string, mime = "text/html") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
